### ISSUE TITLE
I‘m finding a writeup about "web-oldapi",anyone can give me please?有人有官方wp吗，我想看看web的oldapi

### ISSUE THREAD

**Issue by youyou-pm10** [CTF-Archives/2024-dfjk#1]
I‘m finding a writeup about "web-oldapi",anyone can give me please?有人有官方wp吗，我想看看web的oldapi

**Comment by Randark-JMT** [comment]
目前来看，官方没有放出官方writeup，同时民间没有oldapi的wp，抱歉
